//*****************************************************************************
//*****************************************************************************
//  FILENAME: HeartBeatTimer.h
//   Version: 2.6, Updated on 2009/10/15 at 17:11:37
//  Generated by PSoC Designer 5.0.1127.0
//
//  DESCRIPTION: Timer16 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2009. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#include <m8c.h>

#pragma fastcall16 HeartBeatTimer_EnableInt
#pragma fastcall16 HeartBeatTimer_DisableInt
#pragma fastcall16 HeartBeatTimer_Start
#pragma fastcall16 HeartBeatTimer_Stop
#pragma fastcall16 HeartBeatTimer_wReadTimer                // Read  DR0
#pragma fastcall16 HeartBeatTimer_wReadTimerSaveCV          // Read  DR0      
#pragma fastcall16 HeartBeatTimer_WritePeriod               // Write DR1
#pragma fastcall16 HeartBeatTimer_wReadCompareValue         // Read  DR2
#pragma fastcall16 HeartBeatTimer_WriteCompareValue         // Write DR2

// The following symbols are deprecated.
// They may be omitted in future releases
//
#pragma fastcall16 wHeartBeatTimer_ReadCounter              // Read  DR0 "Obsolete"
#pragma fastcall16 wHeartBeatTimer_CaptureCounter           // Read  DR0 "Obsolete"
#pragma fastcall16 wHeartBeatTimer_ReadTimer                // Read  DR0 (Deprecated)
#pragma fastcall16 wHeartBeatTimer_ReadTimerSaveCV          // Read  DR0 (Deprecated)
#pragma fastcall16 wHeartBeatTimer_ReadCompareValue         // Read  DR2 (Deprecated)


//-------------------------------------------------
// Prototypes of the HeartBeatTimer API.
//-------------------------------------------------

extern void HeartBeatTimer_EnableInt(void);                           // Proxy 1
extern void HeartBeatTimer_DisableInt(void);                          // Proxy 1
extern void HeartBeatTimer_Start(void);                               // Proxy 1
extern void HeartBeatTimer_Stop(void);                                // Proxy 1
extern WORD HeartBeatTimer_wReadTimer(void);                          // Proxy 1
extern WORD HeartBeatTimer_wReadTimerSaveCV(void);                    // Proxy 2
extern void HeartBeatTimer_WritePeriod(WORD wPeriod);                 // Proxy 1
extern WORD HeartBeatTimer_wReadCompareValue(void);                   // Proxy 1
extern void HeartBeatTimer_WriteCompareValue(WORD wCompareValue);     // Proxy 1

// The following functions are deprecated.
// They may be omitted in future releases
//
extern WORD wHeartBeatTimer_ReadCompareValue(void);       // Deprecated
extern WORD wHeartBeatTimer_ReadTimerSaveCV(void);        // Deprecated
extern WORD wHeartBeatTimer_ReadCounter(void);            // Obsolete
extern WORD wHeartBeatTimer_ReadTimer(void);              // Deprecated
extern WORD wHeartBeatTimer_CaptureCounter(void);         // Obsolete


//--------------------------------------------------
// Constants for HeartBeatTimer API's.
//--------------------------------------------------

#define HeartBeatTimer_CONTROL_REG_START_BIT   ( 0x01 )
#define HeartBeatTimer_INT_REG_ADDR            ( 0x0df )
#define HeartBeatTimer_INT_MASK                ( 0x02 )


//--------------------------------------------------
// Constants for HeartBeatTimer user defined values
//--------------------------------------------------

#define HeartBeatTimer_PERIOD                  ( 0xc7f )
#define HeartBeatTimer_COMPARE_VALUE           ( 0x0 )


//-------------------------------------------------
// Register Addresses for HeartBeatTimer
//-------------------------------------------------

#pragma ioport  HeartBeatTimer_COUNTER_LSB_REG: 0x040      //Count register LSB
BYTE            HeartBeatTimer_COUNTER_LSB_REG;
#pragma ioport  HeartBeatTimer_COUNTER_MSB_REG: 0x044      //Count register MSB
BYTE            HeartBeatTimer_COUNTER_MSB_REG;
#pragma ioport  HeartBeatTimer_PERIOD_LSB_REG:  0x041      //Period register LSB
BYTE            HeartBeatTimer_PERIOD_LSB_REG;
#pragma ioport  HeartBeatTimer_PERIOD_MSB_REG:  0x045      //Period register MSB
BYTE            HeartBeatTimer_PERIOD_MSB_REG;
#pragma ioport  HeartBeatTimer_COMPARE_LSB_REG: 0x042      //Compare register LSB
BYTE            HeartBeatTimer_COMPARE_LSB_REG;
#pragma ioport  HeartBeatTimer_COMPARE_MSB_REG: 0x046      //Compare register MSB
BYTE            HeartBeatTimer_COMPARE_MSB_REG;
#pragma ioport  HeartBeatTimer_CONTROL_LSB_REG: 0x043      //Control register LSB
BYTE            HeartBeatTimer_CONTROL_LSB_REG;
#pragma ioport  HeartBeatTimer_CONTROL_MSB_REG: 0x047      //Control register MSB
BYTE            HeartBeatTimer_CONTROL_MSB_REG;
#pragma ioport  HeartBeatTimer_FUNC_LSB_REG:    0x140      //Function register LSB
BYTE            HeartBeatTimer_FUNC_LSB_REG;
#pragma ioport  HeartBeatTimer_FUNC_MSB_REG:    0x144      //Function register MSB
BYTE            HeartBeatTimer_FUNC_MSB_REG;
#pragma ioport  HeartBeatTimer_INPUT_LSB_REG:   0x141      //Input register LSB
BYTE            HeartBeatTimer_INPUT_LSB_REG;
#pragma ioport  HeartBeatTimer_INPUT_MSB_REG:   0x145      //Input register MSB
BYTE            HeartBeatTimer_INPUT_MSB_REG;
#pragma ioport  HeartBeatTimer_OUTPUT_LSB_REG:  0x142      //Output register LSB
BYTE            HeartBeatTimer_OUTPUT_LSB_REG;
#pragma ioport  HeartBeatTimer_OUTPUT_MSB_REG:  0x146      //Output register MSB
BYTE            HeartBeatTimer_OUTPUT_MSB_REG;
#pragma ioport  HeartBeatTimer_INT_REG:       0x0df        //Interrupt Mask Register
BYTE            HeartBeatTimer_INT_REG;


//-------------------------------------------------
// HeartBeatTimer Macro 'Functions'
//-------------------------------------------------

#define HeartBeatTimer_Start_M \
   ( HeartBeatTimer_CONTROL_LSB_REG |=  HeartBeatTimer_CONTROL_REG_START_BIT )

#define HeartBeatTimer_Stop_M  \
   ( HeartBeatTimer_CONTROL_LSB_REG &= ~HeartBeatTimer_CONTROL_REG_START_BIT )

#define HeartBeatTimer_EnableInt_M   \
   M8C_EnableIntMask(  HeartBeatTimer_INT_REG, HeartBeatTimer_INT_MASK )

#define HeartBeatTimer_DisableInt_M  \
   M8C_DisableIntMask( HeartBeatTimer_INT_REG, HeartBeatTimer_INT_MASK )


// end of file HeartBeatTimer.h


