/******************************************************************************
*  Generated by PSoC Designer 5.0.1127.0
******************************************************************************/
#include <m8c.h>
// AGND address and mask defines
#pragma	ioport	AGND_Data_ADDR:	0x0
BYTE			AGND_Data_ADDR;
#pragma	ioport	AGND_DriveMode_0_ADDR:	0x100
BYTE			AGND_DriveMode_0_ADDR;
#pragma	ioport	AGND_DriveMode_1_ADDR:	0x101
BYTE			AGND_DriveMode_1_ADDR;
#pragma	ioport	AGND_DriveMode_2_ADDR:	0x3
BYTE			AGND_DriveMode_2_ADDR;
#pragma	ioport	AGND_GlobalSelect_ADDR:	0x2
BYTE			AGND_GlobalSelect_ADDR;
#pragma	ioport	AGND_IntCtrl_0_ADDR:	0x102
BYTE			AGND_IntCtrl_0_ADDR;
#pragma	ioport	AGND_IntCtrl_1_ADDR:	0x103
BYTE			AGND_IntCtrl_1_ADDR;
#pragma	ioport	AGND_IntEn_ADDR:	0x1
BYTE			AGND_IntEn_ADDR;
#define AGND_MASK 0x4
// AnalogOutBuf_2 address and mask defines
#pragma	ioport	AnalogOutBuf_2_Data_ADDR:	0x0
BYTE			AnalogOutBuf_2_Data_ADDR;
#pragma	ioport	AnalogOutBuf_2_DriveMode_0_ADDR:	0x100
BYTE			AnalogOutBuf_2_DriveMode_0_ADDR;
#pragma	ioport	AnalogOutBuf_2_DriveMode_1_ADDR:	0x101
BYTE			AnalogOutBuf_2_DriveMode_1_ADDR;
#pragma	ioport	AnalogOutBuf_2_DriveMode_2_ADDR:	0x3
BYTE			AnalogOutBuf_2_DriveMode_2_ADDR;
#pragma	ioport	AnalogOutBuf_2_GlobalSelect_ADDR:	0x2
BYTE			AnalogOutBuf_2_GlobalSelect_ADDR;
#pragma	ioport	AnalogOutBuf_2_IntCtrl_0_ADDR:	0x102
BYTE			AnalogOutBuf_2_IntCtrl_0_ADDR;
#pragma	ioport	AnalogOutBuf_2_IntCtrl_1_ADDR:	0x103
BYTE			AnalogOutBuf_2_IntCtrl_1_ADDR;
#pragma	ioport	AnalogOutBuf_2_IntEn_ADDR:	0x1
BYTE			AnalogOutBuf_2_IntEn_ADDR;
#define AnalogOutBuf_2_MASK 0x10
// Connect_BPF4_FinalStage_PGA address and mask defines
#pragma	ioport	Connect_BPF4_FinalStage_PGA_Data_ADDR:	0x0
BYTE			Connect_BPF4_FinalStage_PGA_Data_ADDR;
#pragma	ioport	Connect_BPF4_FinalStage_PGA_DriveMode_0_ADDR:	0x100
BYTE			Connect_BPF4_FinalStage_PGA_DriveMode_0_ADDR;
#pragma	ioport	Connect_BPF4_FinalStage_PGA_DriveMode_1_ADDR:	0x101
BYTE			Connect_BPF4_FinalStage_PGA_DriveMode_1_ADDR;
#pragma	ioport	Connect_BPF4_FinalStage_PGA_DriveMode_2_ADDR:	0x3
BYTE			Connect_BPF4_FinalStage_PGA_DriveMode_2_ADDR;
#pragma	ioport	Connect_BPF4_FinalStage_PGA_GlobalSelect_ADDR:	0x2
BYTE			Connect_BPF4_FinalStage_PGA_GlobalSelect_ADDR;
#pragma	ioport	Connect_BPF4_FinalStage_PGA_IntCtrl_0_ADDR:	0x102
BYTE			Connect_BPF4_FinalStage_PGA_IntCtrl_0_ADDR;
#pragma	ioport	Connect_BPF4_FinalStage_PGA_IntCtrl_1_ADDR:	0x103
BYTE			Connect_BPF4_FinalStage_PGA_IntCtrl_1_ADDR;
#pragma	ioport	Connect_BPF4_FinalStage_PGA_IntEn_ADDR:	0x1
BYTE			Connect_BPF4_FinalStage_PGA_IntEn_ADDR;
#define Connect_BPF4_FinalStage_PGA_MASK 0x20
// AnalogColumn_InputMUX_3 address and mask defines
#pragma	ioport	AnalogColumn_InputMUX_3_Data_ADDR:	0x0
BYTE			AnalogColumn_InputMUX_3_Data_ADDR;
#pragma	ioport	AnalogColumn_InputMUX_3_DriveMode_0_ADDR:	0x100
BYTE			AnalogColumn_InputMUX_3_DriveMode_0_ADDR;
#pragma	ioport	AnalogColumn_InputMUX_3_DriveMode_1_ADDR:	0x101
BYTE			AnalogColumn_InputMUX_3_DriveMode_1_ADDR;
#pragma	ioport	AnalogColumn_InputMUX_3_DriveMode_2_ADDR:	0x3
BYTE			AnalogColumn_InputMUX_3_DriveMode_2_ADDR;
#pragma	ioport	AnalogColumn_InputMUX_3_GlobalSelect_ADDR:	0x2
BYTE			AnalogColumn_InputMUX_3_GlobalSelect_ADDR;
#pragma	ioport	AnalogColumn_InputMUX_3_IntCtrl_0_ADDR:	0x102
BYTE			AnalogColumn_InputMUX_3_IntCtrl_0_ADDR;
#pragma	ioport	AnalogColumn_InputMUX_3_IntCtrl_1_ADDR:	0x103
BYTE			AnalogColumn_InputMUX_3_IntCtrl_1_ADDR;
#pragma	ioport	AnalogColumn_InputMUX_3_IntEn_ADDR:	0x1
BYTE			AnalogColumn_InputMUX_3_IntEn_ADDR;
#define AnalogColumn_InputMUX_3_MASK 0x40
// I2CHWSDA address and mask defines
#pragma	ioport	I2CHWSDA_Data_ADDR:	0x4
BYTE			I2CHWSDA_Data_ADDR;
#pragma	ioport	I2CHWSDA_DriveMode_0_ADDR:	0x104
BYTE			I2CHWSDA_DriveMode_0_ADDR;
#pragma	ioport	I2CHWSDA_DriveMode_1_ADDR:	0x105
BYTE			I2CHWSDA_DriveMode_1_ADDR;
#pragma	ioport	I2CHWSDA_DriveMode_2_ADDR:	0x7
BYTE			I2CHWSDA_DriveMode_2_ADDR;
#pragma	ioport	I2CHWSDA_GlobalSelect_ADDR:	0x6
BYTE			I2CHWSDA_GlobalSelect_ADDR;
#pragma	ioport	I2CHWSDA_IntCtrl_0_ADDR:	0x106
BYTE			I2CHWSDA_IntCtrl_0_ADDR;
#pragma	ioport	I2CHWSDA_IntCtrl_1_ADDR:	0x107
BYTE			I2CHWSDA_IntCtrl_1_ADDR;
#pragma	ioport	I2CHWSDA_IntEn_ADDR:	0x5
BYTE			I2CHWSDA_IntEn_ADDR;
#define I2CHWSDA_MASK 0x20
// I2CHWSCL address and mask defines
#pragma	ioport	I2CHWSCL_Data_ADDR:	0x4
BYTE			I2CHWSCL_Data_ADDR;
#pragma	ioport	I2CHWSCL_DriveMode_0_ADDR:	0x104
BYTE			I2CHWSCL_DriveMode_0_ADDR;
#pragma	ioport	I2CHWSCL_DriveMode_1_ADDR:	0x105
BYTE			I2CHWSCL_DriveMode_1_ADDR;
#pragma	ioport	I2CHWSCL_DriveMode_2_ADDR:	0x7
BYTE			I2CHWSCL_DriveMode_2_ADDR;
#pragma	ioport	I2CHWSCL_GlobalSelect_ADDR:	0x6
BYTE			I2CHWSCL_GlobalSelect_ADDR;
#pragma	ioport	I2CHWSCL_IntCtrl_0_ADDR:	0x106
BYTE			I2CHWSCL_IntCtrl_0_ADDR;
#pragma	ioport	I2CHWSCL_IntCtrl_1_ADDR:	0x107
BYTE			I2CHWSCL_IntCtrl_1_ADDR;
#pragma	ioport	I2CHWSCL_IntEn_ADDR:	0x5
BYTE			I2CHWSCL_IntEn_ADDR;
#define I2CHWSCL_MASK 0x80
// DIGITAL_OUTPin address and mask defines
#pragma	ioport	DIGITAL_OUTPin_Data_ADDR:	0x8
BYTE			DIGITAL_OUTPin_Data_ADDR;
#pragma	ioport	DIGITAL_OUTPin_DriveMode_0_ADDR:	0x108
BYTE			DIGITAL_OUTPin_DriveMode_0_ADDR;
#pragma	ioport	DIGITAL_OUTPin_DriveMode_1_ADDR:	0x109
BYTE			DIGITAL_OUTPin_DriveMode_1_ADDR;
#pragma	ioport	DIGITAL_OUTPin_DriveMode_2_ADDR:	0xb
BYTE			DIGITAL_OUTPin_DriveMode_2_ADDR;
#pragma	ioport	DIGITAL_OUTPin_GlobalSelect_ADDR:	0xa
BYTE			DIGITAL_OUTPin_GlobalSelect_ADDR;
#pragma	ioport	DIGITAL_OUTPin_IntCtrl_0_ADDR:	0x10a
BYTE			DIGITAL_OUTPin_IntCtrl_0_ADDR;
#pragma	ioport	DIGITAL_OUTPin_IntCtrl_1_ADDR:	0x10b
BYTE			DIGITAL_OUTPin_IntCtrl_1_ADDR;
#pragma	ioport	DIGITAL_OUTPin_IntEn_ADDR:	0x9
BYTE			DIGITAL_OUTPin_IntEn_ADDR;
#define DIGITAL_OUTPin_MASK 0x10
// DIGITAL_OUTPin Shadow defines
//   DIGITAL_OUTPin_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define DIGITAL_OUTPin_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// LED_3Pin address and mask defines
#pragma	ioport	LED_3Pin_Data_ADDR:	0x8
BYTE			LED_3Pin_Data_ADDR;
#pragma	ioport	LED_3Pin_DriveMode_0_ADDR:	0x108
BYTE			LED_3Pin_DriveMode_0_ADDR;
#pragma	ioport	LED_3Pin_DriveMode_1_ADDR:	0x109
BYTE			LED_3Pin_DriveMode_1_ADDR;
#pragma	ioport	LED_3Pin_DriveMode_2_ADDR:	0xb
BYTE			LED_3Pin_DriveMode_2_ADDR;
#pragma	ioport	LED_3Pin_GlobalSelect_ADDR:	0xa
BYTE			LED_3Pin_GlobalSelect_ADDR;
#pragma	ioport	LED_3Pin_IntCtrl_0_ADDR:	0x10a
BYTE			LED_3Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED_3Pin_IntCtrl_1_ADDR:	0x10b
BYTE			LED_3Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED_3Pin_IntEn_ADDR:	0x9
BYTE			LED_3Pin_IntEn_ADDR;
#define LED_3Pin_MASK 0x20
// LED_3Pin Shadow defines
//   LED_3Pin_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LED_3Pin_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// LED_2Pin address and mask defines
#pragma	ioport	LED_2Pin_Data_ADDR:	0x8
BYTE			LED_2Pin_Data_ADDR;
#pragma	ioport	LED_2Pin_DriveMode_0_ADDR:	0x108
BYTE			LED_2Pin_DriveMode_0_ADDR;
#pragma	ioport	LED_2Pin_DriveMode_1_ADDR:	0x109
BYTE			LED_2Pin_DriveMode_1_ADDR;
#pragma	ioport	LED_2Pin_DriveMode_2_ADDR:	0xb
BYTE			LED_2Pin_DriveMode_2_ADDR;
#pragma	ioport	LED_2Pin_GlobalSelect_ADDR:	0xa
BYTE			LED_2Pin_GlobalSelect_ADDR;
#pragma	ioport	LED_2Pin_IntCtrl_0_ADDR:	0x10a
BYTE			LED_2Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED_2Pin_IntCtrl_1_ADDR:	0x10b
BYTE			LED_2Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED_2Pin_IntEn_ADDR:	0x9
BYTE			LED_2Pin_IntEn_ADDR;
#define LED_2Pin_MASK 0x40
// LED_2Pin Shadow defines
//   LED_2Pin_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LED_2Pin_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
// LED_1Pin address and mask defines
#pragma	ioport	LED_1Pin_Data_ADDR:	0x8
BYTE			LED_1Pin_Data_ADDR;
#pragma	ioport	LED_1Pin_DriveMode_0_ADDR:	0x108
BYTE			LED_1Pin_DriveMode_0_ADDR;
#pragma	ioport	LED_1Pin_DriveMode_1_ADDR:	0x109
BYTE			LED_1Pin_DriveMode_1_ADDR;
#pragma	ioport	LED_1Pin_DriveMode_2_ADDR:	0xb
BYTE			LED_1Pin_DriveMode_2_ADDR;
#pragma	ioport	LED_1Pin_GlobalSelect_ADDR:	0xa
BYTE			LED_1Pin_GlobalSelect_ADDR;
#pragma	ioport	LED_1Pin_IntCtrl_0_ADDR:	0x10a
BYTE			LED_1Pin_IntCtrl_0_ADDR;
#pragma	ioport	LED_1Pin_IntCtrl_1_ADDR:	0x10b
BYTE			LED_1Pin_IntCtrl_1_ADDR;
#pragma	ioport	LED_1Pin_IntEn_ADDR:	0x9
BYTE			LED_1Pin_IntEn_ADDR;
#define LED_1Pin_MASK 0x80
// LED_1Pin Shadow defines
//   LED_1Pin_DataShadow define
extern BYTE Port_2_Data_SHADE;
#define LED_1Pin_DataShadow (*(unsigned char*)&Port_2_Data_SHADE)
