//*****************************************************************************
//*****************************************************************************
//  FILENAME:  SCBLOCK_inbuff1.h  ( SCBLOCK )
//  Version: 2.4, Updated on 2009/10/15 at 17:11:37
//  Generated by PSoC Designer 5.0.1127.0
//
//  DESCRIPTION:  SCBLOCK User Module C Language interface file.
//
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress Semiconductor 2009. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#include <M8C.h>

//-------------------------------------------------
// Constants for SCBLOCK_inbuff1 API's.
//-------------------------------------------------
#define SCBLOCK_inbuff1_OFF         0
#define SCBLOCK_inbuff1_LOWPOWER    1
#define SCBLOCK_inbuff1_MEDPOWER    2
#define SCBLOCK_inbuff1_HIGHPOWER   3

#pragma fastcall16 SCBLOCK_inbuff1_Start
#pragma fastcall16 SCBLOCK_inbuff1_SetPower
#pragma fastcall16 SCBLOCK_inbuff1_Stop

//-------------------------------------------------
// Prototypes of the SCBLOCK_inbuff1 API.
//-------------------------------------------------
extern void SCBLOCK_inbuff1_Start(BYTE bPower);
extern void SCBLOCK_inbuff1_SetPower(BYTE bPower);
extern void SCBLOCK_inbuff1_Stop(void);

//-------------------------------------------------
// Register Addresses for SCBLOCK_inbuff1
//-------------------------------------------------
#pragma ioport  SCBLOCK_inbuff1_cr0:    0x09c
BYTE            SCBLOCK_inbuff1_cr0;
#pragma ioport  SCBLOCK_inbuff1_cr1:    0x09d
BYTE            SCBLOCK_inbuff1_cr1;
#pragma ioport  SCBLOCK_inbuff1_cr2:    0x09e
BYTE            SCBLOCK_inbuff1_cr2;
#pragma ioport  SCBLOCK_inbuff1_cr3:    0x09f
BYTE            SCBLOCK_inbuff1_cr3;
#pragma ioport  SCBLOCK_inbuff1_Comp_Ctrl:  0x000
BYTE            SCBLOCK_inbuff1_Comp_Ctrl;

// end of file SCBLOCK_inbuff1.h
