//*****************************************************************************
//*****************************************************************************
//  FILENAME: HB_Tmr.h
//   Version: 2.6, Updated on 2009/10/15 at 17:11:37
//  Generated by PSoC Designer 5.0.1127.0
//
//  DESCRIPTION: Timer16 User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2009. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#include <m8c.h>

#pragma fastcall16 HB_Tmr_EnableInt
#pragma fastcall16 HB_Tmr_DisableInt
#pragma fastcall16 HB_Tmr_Start
#pragma fastcall16 HB_Tmr_Stop
#pragma fastcall16 HB_Tmr_wReadTimer                // Read  DR0
#pragma fastcall16 HB_Tmr_wReadTimerSaveCV          // Read  DR0      
#pragma fastcall16 HB_Tmr_WritePeriod               // Write DR1
#pragma fastcall16 HB_Tmr_wReadCompareValue         // Read  DR2
#pragma fastcall16 HB_Tmr_WriteCompareValue         // Write DR2

// The following symbols are deprecated.
// They may be omitted in future releases
//
#pragma fastcall16 wHB_Tmr_ReadCounter              // Read  DR0 "Obsolete"
#pragma fastcall16 wHB_Tmr_CaptureCounter           // Read  DR0 "Obsolete"
#pragma fastcall16 wHB_Tmr_ReadTimer                // Read  DR0 (Deprecated)
#pragma fastcall16 wHB_Tmr_ReadTimerSaveCV          // Read  DR0 (Deprecated)
#pragma fastcall16 wHB_Tmr_ReadCompareValue         // Read  DR2 (Deprecated)


//-------------------------------------------------
// Prototypes of the HB_Tmr API.
//-------------------------------------------------

extern void HB_Tmr_EnableInt(void);                           // Proxy 1
extern void HB_Tmr_DisableInt(void);                          // Proxy 1
extern void HB_Tmr_Start(void);                               // Proxy 1
extern void HB_Tmr_Stop(void);                                // Proxy 1
extern WORD HB_Tmr_wReadTimer(void);                          // Proxy 1
extern WORD HB_Tmr_wReadTimerSaveCV(void);                    // Proxy 2
extern void HB_Tmr_WritePeriod(WORD wPeriod);                 // Proxy 1
extern WORD HB_Tmr_wReadCompareValue(void);                   // Proxy 1
extern void HB_Tmr_WriteCompareValue(WORD wCompareValue);     // Proxy 1

// The following functions are deprecated.
// They may be omitted in future releases
//
extern WORD wHB_Tmr_ReadCompareValue(void);       // Deprecated
extern WORD wHB_Tmr_ReadTimerSaveCV(void);        // Deprecated
extern WORD wHB_Tmr_ReadCounter(void);            // Obsolete
extern WORD wHB_Tmr_ReadTimer(void);              // Deprecated
extern WORD wHB_Tmr_CaptureCounter(void);         // Obsolete


//--------------------------------------------------
// Constants for HB_Tmr API's.
//--------------------------------------------------

#define HB_Tmr_CONTROL_REG_START_BIT           ( 0x01 )
#define HB_Tmr_INT_REG_ADDR                    ( 0x0df )
#define HB_Tmr_INT_MASK                        ( 0x02 )


//--------------------------------------------------
// Constants for HB_Tmr user defined values
//--------------------------------------------------

#define HB_Tmr_PERIOD                          ( 0xc7f )
#define HB_Tmr_COMPARE_VALUE                   ( 0x0 )


//-------------------------------------------------
// Register Addresses for HB_Tmr
//-------------------------------------------------

#pragma ioport  HB_Tmr_COUNTER_LSB_REG: 0x040              //Count register LSB
BYTE            HB_Tmr_COUNTER_LSB_REG;
#pragma ioport  HB_Tmr_COUNTER_MSB_REG: 0x044              //Count register MSB
BYTE            HB_Tmr_COUNTER_MSB_REG;
#pragma ioport  HB_Tmr_PERIOD_LSB_REG:  0x041              //Period register LSB
BYTE            HB_Tmr_PERIOD_LSB_REG;
#pragma ioport  HB_Tmr_PERIOD_MSB_REG:  0x045              //Period register MSB
BYTE            HB_Tmr_PERIOD_MSB_REG;
#pragma ioport  HB_Tmr_COMPARE_LSB_REG: 0x042              //Compare register LSB
BYTE            HB_Tmr_COMPARE_LSB_REG;
#pragma ioport  HB_Tmr_COMPARE_MSB_REG: 0x046              //Compare register MSB
BYTE            HB_Tmr_COMPARE_MSB_REG;
#pragma ioport  HB_Tmr_CONTROL_LSB_REG: 0x043              //Control register LSB
BYTE            HB_Tmr_CONTROL_LSB_REG;
#pragma ioport  HB_Tmr_CONTROL_MSB_REG: 0x047              //Control register MSB
BYTE            HB_Tmr_CONTROL_MSB_REG;
#pragma ioport  HB_Tmr_FUNC_LSB_REG:    0x140              //Function register LSB
BYTE            HB_Tmr_FUNC_LSB_REG;
#pragma ioport  HB_Tmr_FUNC_MSB_REG:    0x144              //Function register MSB
BYTE            HB_Tmr_FUNC_MSB_REG;
#pragma ioport  HB_Tmr_INPUT_LSB_REG:   0x141              //Input register LSB
BYTE            HB_Tmr_INPUT_LSB_REG;
#pragma ioport  HB_Tmr_INPUT_MSB_REG:   0x145              //Input register MSB
BYTE            HB_Tmr_INPUT_MSB_REG;
#pragma ioport  HB_Tmr_OUTPUT_LSB_REG:  0x142              //Output register LSB
BYTE            HB_Tmr_OUTPUT_LSB_REG;
#pragma ioport  HB_Tmr_OUTPUT_MSB_REG:  0x146              //Output register MSB
BYTE            HB_Tmr_OUTPUT_MSB_REG;
#pragma ioport  HB_Tmr_INT_REG:       0x0df                //Interrupt Mask Register
BYTE            HB_Tmr_INT_REG;


//-------------------------------------------------
// HB_Tmr Macro 'Functions'
//-------------------------------------------------

#define HB_Tmr_Start_M \
   ( HB_Tmr_CONTROL_LSB_REG |=  HB_Tmr_CONTROL_REG_START_BIT )

#define HB_Tmr_Stop_M  \
   ( HB_Tmr_CONTROL_LSB_REG &= ~HB_Tmr_CONTROL_REG_START_BIT )

#define HB_Tmr_EnableInt_M   \
   M8C_EnableIntMask(  HB_Tmr_INT_REG, HB_Tmr_INT_MASK )

#define HB_Tmr_DisableInt_M  \
   M8C_DisableIntMask( HB_Tmr_INT_REG, HB_Tmr_INT_MASK )


// end of file HB_Tmr.h


