//*****************************************************************************
//*****************************************************************************
//  FILENAME:  SCBLOCK_inbuff2.h  ( SCBLOCK )
//  Version: 2.4, Updated on 2009/10/15 at 17:11:37
//  Generated by PSoC Designer 5.0.1127.0
//
//  DESCRIPTION:  SCBLOCK User Module C Language interface file.
//
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress Semiconductor 2009. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#include <M8C.h>

//-------------------------------------------------
// Constants for SCBLOCK_inbuff2 API's.
//-------------------------------------------------
#define SCBLOCK_inbuff2_OFF         0
#define SCBLOCK_inbuff2_LOWPOWER    1
#define SCBLOCK_inbuff2_MEDPOWER    2
#define SCBLOCK_inbuff2_HIGHPOWER   3

#pragma fastcall16 SCBLOCK_inbuff2_Start
#pragma fastcall16 SCBLOCK_inbuff2_SetPower
#pragma fastcall16 SCBLOCK_inbuff2_Stop

//-------------------------------------------------
// Prototypes of the SCBLOCK_inbuff2 API.
//-------------------------------------------------
extern void SCBLOCK_inbuff2_Start(BYTE bPower);
extern void SCBLOCK_inbuff2_SetPower(BYTE bPower);
extern void SCBLOCK_inbuff2_Stop(void);

//-------------------------------------------------
// Register Addresses for SCBLOCK_inbuff2
//-------------------------------------------------
#pragma ioport  SCBLOCK_inbuff2_cr0:    0x098
BYTE            SCBLOCK_inbuff2_cr0;
#pragma ioport  SCBLOCK_inbuff2_cr1:    0x099
BYTE            SCBLOCK_inbuff2_cr1;
#pragma ioport  SCBLOCK_inbuff2_cr2:    0x09a
BYTE            SCBLOCK_inbuff2_cr2;
#pragma ioport  SCBLOCK_inbuff2_cr3:    0x09b
BYTE            SCBLOCK_inbuff2_cr3;
#pragma ioport  SCBLOCK_inbuff2_Comp_Ctrl:  0x000
BYTE            SCBLOCK_inbuff2_Comp_Ctrl;

// end of file SCBLOCK_inbuff2.h
