//*****************************************************************************
//*****************************************************************************
//  FILENAME: DIGITAL_OUT.h
//   Version: 1.2, Updated on 2009/10/9 at 10:6:29                                          
//  Generated by PSoC Designer 5.0.1127.0
//
//  DESCRIPTION: DIGITAL_OUT User Module C Language interface file
//-----------------------------------------------------------------------------
//  Copyright (c) Cypress Semiconductor 2009. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#include <m8c.h>


/* Create pragmas to support proper argument and return value passing */
#pragma fastcall16  DIGITAL_OUT_Stop
#pragma fastcall16  DIGITAL_OUT_Start
#pragma fastcall16  DIGITAL_OUT_On
#pragma fastcall16  DIGITAL_OUT_Off
#pragma fastcall16  DIGITAL_OUT_Switch
#pragma fastcall16  DIGITAL_OUT_Invert
#pragma fastcall16  DIGITAL_OUT_GetState


//-------------------------------------------------
// Constants for DIGITAL_OUT API's.
//-------------------------------------------------
//
#define  DIGITAL_OUT_ON   1
#define  DIGITAL_OUT_OFF  0

//-------------------------------------------------
// Prototypes of the DIGITAL_OUT API.
//-------------------------------------------------
extern void  DIGITAL_OUT_Start(void);                                     
extern void  DIGITAL_OUT_Stop(void);                                      
extern void  DIGITAL_OUT_On(void);                                      
extern void  DIGITAL_OUT_Off(void);                                      
extern void  DIGITAL_OUT_Switch(BYTE bSwitch);
extern void  DIGITAL_OUT_Invert(void);                                         
extern BYTE  DIGITAL_OUT_GetState(void);                                         

//-------------------------------------------------
// Define global variables.                 
//-------------------------------------------------




