//*****************************************************************************
//*****************************************************************************
//  FILENAME:  SCBLOCK_inbuff.h  ( SCBLOCK )
//  Version: 2.4, Updated on 2009/10/15 at 17:11:37
//  Generated by PSoC Designer 5.0.1127.0
//
//  DESCRIPTION:  SCBLOCK User Module C Language interface file.
//
//-----------------------------------------------------------------------------
//      Copyright (c) Cypress Semiconductor 2009. All Rights Reserved.
//*****************************************************************************
//*****************************************************************************

#include <M8C.h>

//-------------------------------------------------
// Constants for SCBLOCK_inbuff API's.
//-------------------------------------------------
#define SCBLOCK_inbuff_OFF         0
#define SCBLOCK_inbuff_LOWPOWER    1
#define SCBLOCK_inbuff_MEDPOWER    2
#define SCBLOCK_inbuff_HIGHPOWER   3

#pragma fastcall16 SCBLOCK_inbuff_Start
#pragma fastcall16 SCBLOCK_inbuff_SetPower
#pragma fastcall16 SCBLOCK_inbuff_Stop

//-------------------------------------------------
// Prototypes of the SCBLOCK_inbuff API.
//-------------------------------------------------
extern void SCBLOCK_inbuff_Start(BYTE bPower);
extern void SCBLOCK_inbuff_SetPower(BYTE bPower);
extern void SCBLOCK_inbuff_Stop(void);

//-------------------------------------------------
// Register Addresses for SCBLOCK_inbuff
//-------------------------------------------------
#pragma ioport  SCBLOCK_inbuff_cr0: 0x09c
BYTE            SCBLOCK_inbuff_cr0;
#pragma ioport  SCBLOCK_inbuff_cr1: 0x09d
BYTE            SCBLOCK_inbuff_cr1;
#pragma ioport  SCBLOCK_inbuff_cr2: 0x09e
BYTE            SCBLOCK_inbuff_cr2;
#pragma ioport  SCBLOCK_inbuff_cr3: 0x09f
BYTE            SCBLOCK_inbuff_cr3;
#pragma ioport  SCBLOCK_inbuff_Comp_Ctrl:   0x000
BYTE            SCBLOCK_inbuff_Comp_Ctrl;

// end of file SCBLOCK_inbuff.h
