PROJNAME=ExplorerSound
DEVICE=CY8C29466
BASEDEVICE=CY8C29000
PROJPATH=C:/PSOC_P~1/EXPLOR~3/EXPLOR~1
PSOCDIR=C:/PROGRA~1/Cypress/Common/CYPRES~3
INCLUDE_PATH=C:/PROGRA~1/Cypress/Common/CYPRES~3/tools/include/CY8C29~1
CSRCS= main.c
LIBCSRCS=
ASMSRCS= delay.asm
LIBASMSRCS= adcincvr_mes.asm adcincvr_mesint.asm adcincvr_pot.asm adcincvr_potint.asm amux4_mic.asm bpf4_4khz.asm digital_out.asm hb_tmr.asm hb_tmrint.asm i2chwcommon.asm i2chwint.asm i2chwrsrcinits.asm led_1.asm led_2.asm led_3.asm pga_out.asm pga_pre.asm psocconfig.asm psocconfigtbl.asm refmux_1.asm scblock_inbuff.asm tx8.asm tx8plus.asm
OBJECT_SOURCES= delay.asm main.c
FILLVALUE=0x30
LASTROM=0x7fff
LASTRAM=0x7ff
LAST_DATARAM=0x6ff
CODECOMPRESSOR=
MORE_CFLAGS=-Wf-nomac -Wf-Osize -Wf-LMM8 -D_LMM
RELSTART=0x1a0
CDEFINES=
LIBS=
UMLIBS=
LIB_PATH=
ENABLE_ALIGN_SHIFT=0
LMM=1
SYS_INC_CONTENTS:=SYSTEM_STACK_PAGE:_equ_7 SYSTEM_STACK_BASE_ADDR:_equ_0h SYSTEM_LARGE_MEMORY_MODEL:_equ_1 SYSTEM_SMALL_MEMORY_MODEL:_equ_0 IMAGECRAFT:_equ_1 HITECH:_equ_2 TOOLCHAIN:_equ_IMAGECRAFT 
SYSTEM_TOOLS=1
CSFLOW=
CONFIG_NAMES=explorersound 
