; Generated by PSoC Designer 5.0.1127.0
;
include "m8c.inc"
;  Personalization tables 
export LoadConfigTBL_explorersound_Bank1
export LoadConfigTBL_explorersound_Bank0
export LoadConfigTBL_explorersound_Ordered
AREA lit(rom, rel)
LoadConfigTBL_explorersound_Bank0:
;  Instance name ADCINCVR_mes, User Module ADCINCVR
;       Instance name ADCINCVR_mes, Block Name ADC(ASD13)
	db		8ch, 90h		;ADCINCVR_mes_bfAtoDcr0       (ASD13CR0)
	db		8dh, 20h		;ADCINCVR_mes_bfAtoDcr1       (ASD13CR1)
	db		8eh, 61h		;ADCINCVR_mes_bfAtoDcr2       (ASD13CR2)
	db		8fh, f0h		;ADCINCVR_mes_bfAtoDcr3       (ASD13CR3)
;       Instance name ADCINCVR_mes, Block Name CNT(DBB00)
	db		23h, 00h		;ADCINCVR_mes_bCounter_CR0    (DBB00CR0)
	db		21h, 00h		;ADCINCVR_mes_bPeriod         (DBB00DR1)
	db		22h, 00h		;ADCINCVR_mes_bCompare        (DBB00DR2)
;       Instance name ADCINCVR_mes, Block Name PWM16_LSB(DBB01)
	db		27h, 00h		;ADCINCVR_mes_fPWM_LSB_CR0    (DBB01CR0)
	db		25h, 00h		;ADCINCVR_mes_bPWM_Period_LSB (DBB01DR1)
	db		26h, 00h		;ADCINCVR_mes_bPWM_IntTime_LSB(DBB01DR2)
;       Instance name ADCINCVR_mes, Block Name PWM16_MSB(DCB02)
	db		2bh, 00h		;ADCINCVR_mes_fPWM_MSB_CR0    (DCB02CR0)
	db		29h, 00h		;ADCINCVR_mes_bPWM_Period_MSB (DCB02DR1)
	db		2ah, 00h		;ADCINCVR_mes_bPWM_IntTime_MSB(DCB02DR2)
;  Instance name ADCINCVR_pot, User Module ADCINCVR
;       Instance name ADCINCVR_pot, Block Name ADC(ASD22)
	db		98h, d0h		;ADCINCVR_pot_bfAtoDcr0       (ASD22CR0)
	db		99h, 40h		;ADCINCVR_pot_bfAtoDcr1       (ASD22CR1)
	db		9ah, 61h		;ADCINCVR_pot_bfAtoDcr2       (ASD22CR2)
	db		9bh, f0h		;ADCINCVR_pot_bfAtoDcr3       (ASD22CR3)
;       Instance name ADCINCVR_pot, Block Name CNT(DCB03)
	db		2fh, 00h		;ADCINCVR_pot_bCounter_CR0    (DCB03CR0)
	db		2dh, 00h		;ADCINCVR_pot_bPeriod         (DCB03DR1)
	db		2eh, 00h		;ADCINCVR_pot_bCompare        (DCB03DR2)
;       Instance name ADCINCVR_pot, Block Name PWM16_LSB(DBB10)
	db		33h, 00h		;ADCINCVR_pot_fPWM_LSB_CR0    (DBB10CR0)
	db		31h, 00h		;ADCINCVR_pot_bPWM_Period_LSB (DBB10DR1)
	db		32h, 00h		;ADCINCVR_pot_bPWM_IntTime_LSB(DBB10DR2)
;       Instance name ADCINCVR_pot, Block Name PWM16_MSB(DBB11)
	db		37h, 00h		;ADCINCVR_pot_fPWM_MSB_CR0    (DBB11CR0)
	db		35h, 00h		;ADCINCVR_pot_bPWM_Period_MSB (DBB11DR1)
	db		36h, 00h		;ADCINCVR_pot_bPWM_IntTime_MSB(DBB11DR2)
;  Instance name AMUX4_mic, User Module AMUX4
;  Instance name BPF4_4KHz, User Module BPF4
;       Instance name BPF4_4KHz, Block Name FLFBH(ASD11)
	db		84h, 85h		;BPF4_4KHz_FLFBH_CR0(ASD11CR0)
	db		85h, 60h		;BPF4_4KHz_FLFBH_CR1(ASD11CR1)
	db		86h, 00h		;BPF4_4KHz_FLFBH_CR2(ASD11CR2)
	db		87h, 20h		;BPF4_4KHz_FLFBH_CR3(ASD11CR3)
;       Instance name BPF4_4KHz, Block Name FLFBL(ASD20)
	db		90h, 85h		;BPF4_4KHz_FLFBL_CR0(ASD20CR0)
	db		91h, 00h		;BPF4_4KHz_FLFBL_CR1(ASD20CR1)
	db		92h, 00h		;BPF4_4KHz_FLFBL_CR2(ASD20CR2)
	db		93h, 20h		;BPF4_4KHz_FLFBL_CR3(ASD20CR3)
;       Instance name BPF4_4KHz, Block Name FLINH(ASC21)
	db		94h, a1h		;BPF4_4KHz_FLINH_CR0(ASC21CR0)
	db		95h, 94h		;BPF4_4KHz_FLINH_CR1(ASC21CR1)
	db		96h, 85h		;BPF4_4KHz_FLINH_CR2(ASC21CR2)
	db		97h, 20h		;BPF4_4KHz_FLINH_CR3(ASC21CR3)
;       Instance name BPF4_4KHz, Block Name FLINL(ASC10)
	db		80h, a1h		;BPF4_4KHz_FLINL_CR0(ASC10CR0)
	db		81h, b3h		;BPF4_4KHz_FLINL_CR1(ASC10CR1)
	db		82h, 05h		;BPF4_4KHz_FLINL_CR2(ASC10CR2)
	db		83h, 2ch		;BPF4_4KHz_FLINL_CR3(ASC10CR3)
;  Instance name DIGITAL_OUT, User Module LED
;  Instance name HB_Tmr, User Module Timer16
;       Instance name HB_Tmr, Block Name TIMER16_LSB(DBB20)
	db		43h, 00h		;HB_Tmr_CONTROL_LSB_REG(DBB20CR0)
	db		41h, 7fh		;HB_Tmr_PERIOD_LSB_REG(DBB20DR1)
	db		42h, 00h		;HB_Tmr_COMPARE_LSB_REG(DBB20DR2)
;       Instance name HB_Tmr, Block Name TIMER16_MSB(DBB21)
	db		47h, 04h		;HB_Tmr_CONTROL_MSB_REG(DBB21CR0)
	db		45h, 0ch		;HB_Tmr_PERIOD_MSB_REG(DBB21DR1)
	db		46h, 00h		;HB_Tmr_COMPARE_MSB_REG(DBB21DR2)
;  Instance name I2CHW, User Module I2CHW
;  Instance name LED_1, User Module LED
;  Instance name LED_2, User Module LED
;  Instance name LED_3, User Module LED
;  Instance name PGA_out, User Module PGA
;       Instance name PGA_out, Block Name GAIN(ACB02)
	db		79h, 1dh		;PGA_out_GAIN_CR0(ACB02CR0)
	db		7ah, a1h		;PGA_out_GAIN_CR1(ACB02CR1)
	db		7bh, 20h		;PGA_out_GAIN_CR2(ACB02CR2)
	db		78h, 00h		;PGA_out_GAIN_CR3(ACB02CR3)
;  Instance name PGA_pre, User Module PGA
;       Instance name PGA_pre, Block Name GAIN(ACB00)
	db		71h, 4dh		;PGA_pre_GAIN_CR0(ACB00CR0)
	db		72h, a1h		;PGA_pre_GAIN_CR1(ACB00CR1)
	db		73h, 20h		;PGA_pre_GAIN_CR2(ACB00CR2)
	db		70h, 00h		;PGA_pre_GAIN_CR3(ACB00CR3)
;  Instance name RefMux_1, User Module RefMux
;       Instance name RefMux_1, Block Name REFMUX(ACB03)
	db		7dh, 01h		;RefMux_1_REFMUX_CR0(ACB03CR0)
	db		7eh, 09h		;RefMux_1_REFMUX_CR1(ACB03CR1)
	db		7fh, 14h		;RefMux_1_REFMUX_CR2(ACB03CR2)
	db		7ch, 00h		;RefMux_1_REFMUX_CR3(ACB03CR3)
;  Instance name SCBLOCK_inbuff, User Module SCBLOCK
;       Instance name SCBLOCK_inbuff, Block Name SCBLK(ASC23)
	db		9ch, 00h		;SCBLOCK_inbuff_cr0(ASC23CR0)
	db		9dh, 51h		;SCBLOCK_inbuff_cr1(ASC23CR1)
	db		9eh, 20h		;SCBLOCK_inbuff_cr2(ASC23CR2)
	db		9fh, 3bh		;SCBLOCK_inbuff_cr3(ASC23CR3)
;  Instance name TX8, User Module TX8
;       Instance name TX8, Block Name TX8(DCB13)
	db		3fh, 00h		;TX8_CONTROL_REG  (DCB13CR0)
	db		3dh, 00h		;TX8_TX_BUFFER_REG(DCB13DR1)
	db		3eh, 00h		;TX8_(DCB13DR2)
;  Global Register values Bank 0
	db		60h, e4h		; AnalogColumnInputSelect register (AMX_IN)
	db		66h, 00h		; AnalogComparatorControl1 register (CMP_CR1)
	db		63h, 57h		; AnalogReferenceControl register (ARF_CR)
	db		65h, 00h		; AnalogSyncControl register (ASY_CR)
	db		e6h, 00h		; DecimatorControl_0 register (DEC_CR0)
	db		e7h, 00h		; DecimatorControl_1 register (DEC_CR1)
	db		d6h, 04h		; I2CConfig register (I2C_CFG)
	db		b0h, 00h		; Row_0_InputMux register (RDI0RI)
	db		b1h, 00h		; Row_0_InputSync register (RDI0SYN)
	db		b2h, 00h		; Row_0_LogicInputAMux register (RDI0IS)
	db		b3h, 33h		; Row_0_LogicSelect_0 register (RDI0LT0)
	db		b4h, 33h		; Row_0_LogicSelect_1 register (RDI0LT1)
	db		b5h, 00h		; Row_0_OutputDrive_0 register (RDI0SRO0)
	db		b6h, 00h		; Row_0_OutputDrive_1 register (RDI0SRO1)
	db		b8h, 55h		; Row_1_InputMux register (RDI1RI)
	db		b9h, 00h		; Row_1_InputSync register (RDI1SYN)
	db		bah, 10h		; Row_1_LogicInputAMux register (RDI1IS)
	db		bbh, 33h		; Row_1_LogicSelect_0 register (RDI1LT0)
	db		bch, 33h		; Row_1_LogicSelect_1 register (RDI1LT1)
	db		bdh, 00h		; Row_1_OutputDrive_0 register (RDI1SRO0)
	db		beh, 04h		; Row_1_OutputDrive_1 register (RDI1SRO1)
	db		c0h, 00h		; Row_2_InputMux register (RDI2RI)
	db		c1h, 00h		; Row_2_InputSync register (RDI2SYN)
	db		c2h, 20h		; Row_2_LogicInputAMux register (RDI2IS)
	db		c3h, 33h		; Row_2_LogicSelect_0 register (RDI2LT0)
	db		c4h, 33h		; Row_2_LogicSelect_1 register (RDI3LT1)
	db		c5h, 00h		; Row_2_OutputDrive_0 register (RDI2SRO0)
	db		c6h, 00h		; Row_2_OutputDrive_1 register (RDI2SRO1)
	db		c8h, 55h		; Row_3_InputMux register (RDI3RI)
	db		c9h, 00h		; Row_3_InputSync register (RDI3SYN)
	db		cah, 30h		; Row_3_LogicInputAMux register (RDI3IS)
	db		cbh, 33h		; Row_3_LogicSelect_0 register (RDI3LT0)
	db		cch, 33h		; Row_3_LogicSelect_1 register (RDI3LT1)
	db		cdh, 00h		; Row_3_OutputDrive_0 register (RDI3SRO0)
	db		ceh, 00h		; Row_3_OutputDrive_1 register (RDI3SRO1)
	db		6ch, 00h		; TMP_DR0 register (TMP_DR0)
	db		6dh, 00h		; TMP_DR1 register (TMP_DR1)
	db		6eh, 00h		; TMP_DR2 register (TMP_DR2)
	db		6fh, 00h		; TMP_DR3 register (TMP_DR3)
	db		ffh
LoadConfigTBL_explorersound_Bank1:
;  Instance name ADCINCVR_mes, User Module ADCINCVR
;       Instance name ADCINCVR_mes, Block Name ADC(ASD13)
;       Instance name ADCINCVR_mes, Block Name CNT(DBB00)
	db		20h, 21h		;ADCINCVR_mes_fCounterFN      (DBB00FN)
	db		21h, 75h		;ADCINCVR_mes_fCounterSL      (DBB00IN)
	db		22h, 40h		;ADCINCVR_mes_fCounterOS      (DBB00OU)
;       Instance name ADCINCVR_mes, Block Name PWM16_LSB(DBB01)
	db		24h, 01h		;ADCINCVR_mes_bfPWM_LSB_FN    (DBB01FN)
	db		25h, 15h		;ADCINCVR_mes_(DBB01IN)
	db		26h, 40h		;ADCINCVR_mes_(DBB01OU)
;       Instance name ADCINCVR_mes, Block Name PWM16_MSB(DCB02)
	db		28h, 21h		;ADCINCVR_mes_bfPWM_MSB_FN    (DCB02FN)
	db		29h, 35h		;ADCINCVR_mes_(DCB02IN)
	db		2ah, 40h		;ADCINCVR_mes_(DCB02OU)
;  Instance name ADCINCVR_pot, User Module ADCINCVR
;       Instance name ADCINCVR_pot, Block Name ADC(ASD22)
;       Instance name ADCINCVR_pot, Block Name CNT(DCB03)
	db		2ch, 21h		;ADCINCVR_pot_fCounterFN      (DCB03FN)
	db		2dh, 65h		;ADCINCVR_pot_fCounterSL      (DCB03IN)
	db		2eh, 40h		;ADCINCVR_pot_fCounterOS      (DCB03OU)
;       Instance name ADCINCVR_pot, Block Name PWM16_LSB(DBB10)
	db		30h, 01h		;ADCINCVR_pot_bfPWM_LSB_FN    (DBB10FN)
	db		31h, 15h		;ADCINCVR_pot_(DBB10IN)
	db		32h, 40h		;ADCINCVR_pot_(DBB10OU)
;       Instance name ADCINCVR_pot, Block Name PWM16_MSB(DBB11)
	db		34h, 21h		;ADCINCVR_pot_bfPWM_MSB_FN    (DBB11FN)
	db		35h, 35h		;ADCINCVR_pot_(DBB11IN)
	db		36h, 40h		;ADCINCVR_pot_(DBB11OU)
;  Instance name AMUX4_mic, User Module AMUX4
;  Instance name BPF4_4KHz, User Module BPF4
;       Instance name BPF4_4KHz, Block Name FLFBH(ASD11)
;       Instance name BPF4_4KHz, Block Name FLFBL(ASD20)
;       Instance name BPF4_4KHz, Block Name FLINH(ASC21)
;       Instance name BPF4_4KHz, Block Name FLINL(ASC10)
;  Instance name DIGITAL_OUT, User Module LED
;  Instance name HB_Tmr, User Module Timer16
;       Instance name HB_Tmr, Block Name TIMER16_LSB(DBB20)
	db		40h, 10h		;HB_Tmr_FUNC_LSB_REG(DBB20FN)
	db		41h, 06h		;HB_Tmr_INPUT_LSB_REG(DBA20IN)
	db		42h, 40h		;HB_Tmr_OUTPUT_LSB_REG(DBA20OU)
;       Instance name HB_Tmr, Block Name TIMER16_MSB(DBB21)
	db		44h, 30h		;HB_Tmr_FUNC_MSB_REG(DBB21FN)
	db		45h, 36h		;HB_Tmr_INPUT_MSB_REG(DBB21IN)
	db		46h, 40h		;HB_Tmr_OUTPUT_MSB_REG(DBB21OU)
;  Instance name I2CHW, User Module I2CHW
;  Instance name LED_1, User Module LED
;  Instance name LED_2, User Module LED
;  Instance name LED_3, User Module LED
;  Instance name PGA_out, User Module PGA
;       Instance name PGA_out, Block Name GAIN(ACB02)
;  Instance name PGA_pre, User Module PGA
;       Instance name PGA_pre, Block Name GAIN(ACB00)
;  Instance name RefMux_1, User Module RefMux
;       Instance name RefMux_1, Block Name REFMUX(ACB03)
;  Instance name SCBLOCK_inbuff, User Module SCBLOCK
;       Instance name SCBLOCK_inbuff, Block Name SCBLK(ASC23)
;  Instance name TX8, User Module TX8
;       Instance name TX8, Block Name TX8(DCB13)
	db		3ch, 0dh		;TX8_FUNC_REG     (DCB13FN)
	db		3dh, 01h		;TX8_INPUT_REG    (DCB13IN)
	db		3eh, 46h		;TX8_OUTPUT_REG   (DCB13OU)
;  Global Register values Bank 1
	db		61h, 00h		; AnalogClockSelect1 register (CLK_CR1)
	db		69h, 00h		; AnalogClockSelect2 register (CLK_CR2)
	db		60h, 05h		; AnalogColumnClockSelect register (CLK_CR0)
	db		62h, 35h		; AnalogIOControl_0 register (ABF_CR0)
	db		67h, 33h		; AnalogLUTControl0 register (ALT_CR0)
	db		68h, 33h		; AnalogLUTControl1 register (ALT_CR1)
	db		63h, 00h		; AnalogModulatorControl_0 register (AMD_CR0)
	db		66h, 00h		; AnalogModulatorControl_1 register (AMD_CR1)
	db		d1h, 00h		; GlobalDigitalInterconnect_Drive_Even_Input register (GDI_E_IN)
	db		d3h, 00h		; GlobalDigitalInterconnect_Drive_Even_Output register (GDI_E_OU)
	db		d0h, 00h		; GlobalDigitalInterconnect_Drive_Odd_Input register (GDI_O_IN)
	db		d2h, 00h		; GlobalDigitalInterconnect_Drive_Odd_Output register (GDI_O_OU)
	db		e1h, 4eh		; OscillatorControl_1 register (OSC_CR1)
	db		e2h, 00h		; OscillatorControl_2 register (OSC_CR2)
	db		dfh, 19h		; OscillatorControl_3 register (OSC_CR3)
	db		deh, 00h		; OscillatorControl_4 register (OSC_CR4)
	db		ddh, 00h		; OscillatorGlobalBusEnableControl register (OSC_GO_EN)
	db		e7h, 00h		; Type2Decimator_Control register (DEC_CR2)
	db		ffh
LoadConfigTBL_explorersound_Ordered:
;  Ordered Global Register values
	M8C_SetBank1
	mov	reg[00h], 00h		; Port_0_DriveMode_0 register (PRT0DM0)
	mov	reg[01h], ffh		; Port_0_DriveMode_1 register (PRT0DM1)
	M8C_SetBank0
	mov	reg[03h], ffh		; Port_0_DriveMode_2 register (PRT0DM2)
	mov	reg[02h], 00h		; Port_0_GlobalSelect register (PRT0GS)
	M8C_SetBank1
	mov	reg[02h], 00h		; Port_0_IntCtrl_0 register (PRT0IC0)
	mov	reg[03h], 00h		; Port_0_IntCtrl_1 register (PRT0IC1)
	M8C_SetBank0
	mov	reg[01h], 00h		; Port_0_IntEn register (PRT0IE)
	M8C_SetBank1
	mov	reg[04h], a4h		; Port_1_DriveMode_0 register (PRT1DM0)
	mov	reg[05h], fbh		; Port_1_DriveMode_1 register (PRT1DM1)
	M8C_SetBank0
	mov	reg[07h], fbh		; Port_1_DriveMode_2 register (PRT1DM2)
	mov	reg[06h], 04h		; Port_1_GlobalSelect register (PRT1GS)
	M8C_SetBank1
	mov	reg[06h], 00h		; Port_1_IntCtrl_0 register (PRT1IC0)
	mov	reg[07h], 00h		; Port_1_IntCtrl_1 register (PRT1IC1)
	M8C_SetBank0
	mov	reg[05h], 00h		; Port_1_IntEn register (PRT1IE)
	M8C_SetBank1
	mov	reg[08h], f0h		; Port_2_DriveMode_0 register (PRT2DM0)
	mov	reg[09h], 0fh		; Port_2_DriveMode_1 register (PRT2DM1)
	M8C_SetBank0
	mov	reg[0bh], 0fh		; Port_2_DriveMode_2 register (PRT2DM2)
	mov	reg[0ah], 00h		; Port_2_GlobalSelect register (PRT2GS)
	M8C_SetBank1
	mov	reg[0ah], 00h		; Port_2_IntCtrl_0 register (PRT2IC0)
	mov	reg[0bh], 00h		; Port_2_IntCtrl_1 register (PRT2IC1)
	M8C_SetBank0
	mov	reg[09h], 00h		; Port_2_IntEn register (PRT2IE)
	M8C_SetBank1
	mov	reg[0ch], 00h		; Port_3_DriveMode_0 register (PRT3DM0)
	mov	reg[0dh], 00h		; Port_3_DriveMode_1 register (PRT3DM1)
	M8C_SetBank0
	mov	reg[0fh], 00h		; Port_3_DriveMode_2 register (PRT3DM2)
	mov	reg[0eh], 00h		; Port_3_GlobalSelect register (PRT3GS)
	M8C_SetBank1
	mov	reg[0eh], 00h		; Port_3_IntCtrl_0 register (PRT3IC0)
	mov	reg[0fh], 00h		; Port_3_IntCtrl_1 register (PRT3IC1)
	M8C_SetBank0
	mov	reg[0dh], 00h		; Port_3_IntEn register (PRT3IE)
	M8C_SetBank1
	mov	reg[10h], 00h		; Port_4_DriveMode_0 register (PRT4DM0)
	mov	reg[11h], 00h		; Port_4_DriveMode_1 register (PRT4DM1)
	M8C_SetBank0
	mov	reg[13h], 00h		; Port_4_DriveMode_2 register (PRT4DM2)
	mov	reg[12h], 00h		; Port_4_GlobalSelect register (PRT4GS)
	M8C_SetBank1
	mov	reg[12h], 00h		; Port_4_IntCtrl_0 register (PRT4IC0)
	mov	reg[13h], 00h		; Port_4_IntCtrl_1 register (PRT4IC1)
	M8C_SetBank0
	mov	reg[11h], 00h		; Port_4_IntEn register (PRT4IE)
	M8C_SetBank1
	mov	reg[14h], 00h		; Port_5_DriveMode_0 register (PRT5DM0)
	mov	reg[15h], 00h		; Port_5_DriveMode_1 register (PRT5DM1)
	M8C_SetBank0
	mov	reg[17h], 00h		; Port_5_DriveMode_2 register (PRT5DM2)
	mov	reg[16h], 00h		; Port_5_GlobalSelect register (PRT5GS)
	M8C_SetBank1
	mov	reg[16h], 00h		; Port_5_IntCtrl_0 register (PRT5IC0)
	mov	reg[17h], 00h		; Port_5_IntCtrl_1 register (PRT5IC1)
	M8C_SetBank0
	mov	reg[15h], 00h		; Port_5_IntEn register (PRT5IE)
	M8C_SetBank1
	mov	reg[18h], 00h		; Port_6_DriveMode_0 register (PRT6DM0)
	mov	reg[19h], 00h		; Port_6_DriveMode_1 register (PRT6DM1)
	M8C_SetBank0
	mov	reg[1bh], 00h		; Port_6_DriveMode_2 register (PRT6DM2)
	mov	reg[1ah], 00h		; Port_6_GlobalSelect register (PRT6GS)
	M8C_SetBank1
	mov	reg[1ah], 00h		; Port_6_IntCtrl_0 register (PRT6IC0)
	mov	reg[1bh], 00h		; Port_6_IntCtrl_1 register (PRT6IC1)
	M8C_SetBank0
	mov	reg[19h], 00h		; Port_6_IntEn register (PRT6IE)
	M8C_SetBank1
	mov	reg[1ch], 00h		; Port_7_DriveMode_0 register (PRT7DM0)
	mov	reg[1dh], 00h		; Port_7_DriveMode_1 register (PRT7DM1)
	M8C_SetBank0
	mov	reg[1fh], 00h		; Port_7_DriveMode_2 register (PRT7DM2)
	mov	reg[1eh], 00h		; Port_7_GlobalSelect register (PRT7GS)
	M8C_SetBank1
	mov	reg[1eh], 00h		; Port_7_IntCtrl_0 register (PRT7IC0)
	mov	reg[1fh], 00h		; Port_7_IntCtrl_1 register (PRT7IC1)
	M8C_SetBank0
	mov	reg[1dh], 00h		; Port_7_IntEn register (PRT7IE)
	M8C_SetBank0
	ret


; PSoC Configuration file trailer PsocConfig.asm
