/******************************************************************************
*  Generated by PSoC Designer 5.0.1127.0
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "ADCINCVR_mes.h"
#include "ADCINCVR_pot.h"
#include "AMUX4_mic.h"
#include "BPF4_4KHz.h"
#include "DIGITAL_OUT.h"
#include "EzI2Cs_1.h"
#include "HB_Tmr.h"
#include "LED_1.h"
#include "LED_2.h"
#include "LED_3.h"
#include "PGA_out.h"
#include "PGA_pre.h"
#include "RefMux_1.h"
#include "SCBLOCK_inbuff.h"
#include "TX8.h"

#endif
